// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/IndustrialSneakerComparison-3v1DCo/App.tsx": () => import("../components/mockups/templates/IndustrialSneakerComparison-3v1DCo/App.tsx"),
  "./components/mockups/templates/IndustrialSneakerComparison-C_JrlQ/App.tsx": () => import("../components/mockups/templates/IndustrialSneakerComparison-C_JrlQ/App.tsx")
};
